### PR TITLE
Added player.setXRot to snap head to 0 or 45 degree

### PR DESCRIPTION
**Pull request by KingColton1**
Keeps your head look forward rather than slightly down or up. Helps to avoid accidentally interact/open fence, button, and trapdoor during iceroad macro. While you can manually move your head to not touch any of it, but this is more like user convenience. Essentially makes it a little more user friendly.

### CODE REVIEW

**Review by okx-code — CHANGES_REQUESTED** [review]
Could this be added as an option in the ice road config menu as well? So separate "snap to cardinal" to "snap yaw to cardinal" and "snap pitch to cardinal"

**Comment by KingColton1** [comment]
Yeah this can be added as an option

**Comment by KingColton1** [comment]
Updated and separated options for pitch and yaw in iceroad macro my latest commit. Let me know what do you think

**Comment by KingColton1** [comment]
Sure, I've updated and separated options for pitch and yaw in iceroad macro my latest commit.

**Review by KingColton1 — COMMENTED** [review]
Modified to add configs for pitch and yaw + repositioned buttons to be on center

**Pull request merged**
